FROM python:3.10-alpine3.17

ENV LANG="C.UTF-8" \
    TZ="Asia/Shanghai" \
    NASTOOL_CONFIG="/config/config.yaml" \
    NASTOOL_AUTO_UPDATE=false \
    NASTOOL_CN_UPDATE=true \
    NASTOOL_VERSION=lite \
    PS1="\u@\h:\w \$ " \
    REPO_URL="https://github.com/charmmmz/nas-tools.git" \
    PYPI_MIRROR="https://pypi.tuna.tsinghua.edu.cn/simple" \
    ALPINE_MIRROR="mirrors.ustc.edu.cn" \
    PUID=0 \
    PGID=0 \
    UMASK=000 \
    WORKDIR="/nas-tools"

WORKDIR ${WORKDIR}

COPY requirements.txt ./

RUN apk add --no-cache \
        git \
        gcc \
        musl-dev \
        libffi-dev \
        libxml2-dev \
        libxslt-dev \
        tzdata \
        su-exec \
        dumb-init \
        npm \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && ln -sf "$(which python3)" /usr/bin/python \
    && pip install --upgrade "pip<24" "setuptools<66" "wheel<0.42" \
    && pip install "cython<3" \
    && pip install --no-build-isolation -r requirements.txt \
    && npm install pm2 -g \
    && apk del --purge libffi-dev gcc musl-dev libxml2-dev libxslt-dev \
    && pip uninstall -y cython \
    && rm -rf /tmp/* /root/.cache /var/cache/apk/*

COPY . ${WORKDIR}

RUN python3 -c "import os, pathlib, site; pathlib.Path(site.getsitepackages()[0], 'nas-tools.pth').write_text(os.environ['WORKDIR'] + '/\n')" \
    && echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf \
    && echo 'fs.inotify.max_user_instances=524288' >> /etc/sysctl.conf \
    && git config --global pull.ff only \
    && git config --global --add safe.directory ${WORKDIR}

EXPOSE 3000
VOLUME ["/config"]
ENTRYPOINT ["/nas-tools/docker/entrypoint.sh"]
