FROM python:3.10-alpine3.17

ENV LANG="C.UTF-8" \
    TZ="Asia/Shanghai" \
    NASTOOL_CONFIG="/config/config.yaml" \
    NASTOOL_AUTO_UPDATE=false \
    NASTOOL_CN_UPDATE=true \
    NASTOOL_VERSION=custom-beta \
    PS1="\u@\h:\w \$ " \
    REPO_URL="https://github.com/charmmmz/nas-tools.git" \
    PYPI_MIRROR="https://pypi.tuna.tsinghua.edu.cn/simple" \
    ALPINE_MIRROR="mirrors.ustc.edu.cn" \
    PUID=0 \
    PGID=0 \
    UMASK=000 \
    WORKDIR="/nas-tools"

WORKDIR ${WORKDIR}

COPY package_list.txt requirements.txt ./

RUN apk add --no-cache libffi-dev $(grep -Ev '^(python3-dev|py3-pip)$' package_list.txt) \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && ln -sf "$(which python3)" /usr/bin/python \
    && curl https://rclone.org/install.sh | bash \
    && if [ "$(uname -m)" = "x86_64" ]; then ARCH=amd64; elif [ "$(uname -m)" = "aarch64" ]; then ARCH=arm64; fi \
    && curl -fSL https://dl.min.io/client/mc/release/linux-${ARCH}/mc --create-dirs -o /usr/bin/mc \
    && chmod +x /usr/bin/mc \
    && pip install --upgrade "pip<24" "setuptools<66" "wheel<0.42" \
    && pip install "cython<3" \
    && pip install --no-build-isolation -r requirements.txt \
    && npm install pm2 -g \
    && rm -rf /tmp/* /root/.cache /var/cache/apk/*

COPY . ${WORKDIR}

RUN python3 -c "import os, pathlib, site; pathlib.Path(site.getsitepackages()[0], 'nas-tools.pth').write_text(os.environ['WORKDIR'] + '/\n')" \
    && echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf \
    && echo 'fs.inotify.max_user_instances=524288' >> /etc/sysctl.conf \
    && git config --global pull.ff only \
    && git config --global --add safe.directory ${WORKDIR}

EXPOSE 3000
VOLUME ["/config"]
ENTRYPOINT ["/nas-tools/docker/entrypoint.sh"]
